from __future__ import annotations

from pathlib import Path
from typing import Iterable, Protocol


class FileSystemPort(Protocol):
    def iterdir(self, path: Path) -> Iterable[Path]: ...
    def is_dir(self, path: Path) -> bool: ...
    def exists(self, path: Path) -> bool: ...
    def stat(self, path: Path): ...
