from __future__ import annotations

import os
from pathlib import Path
from typing import BinaryIO, Iterator, Protocol


class FileSystemPort(Protocol):
    def mkdir(self, path: Path, *, parents: bool = False, exist_ok: bool = True) -> None: ...
    def exists(self, path: Path) -> bool: ...
    def is_dir(self, path: Path) -> bool: ...
    def is_symlink(self, path: Path) -> bool: ...
    def is_file(self, path: Path) -> bool: ...
    def iterdir(self, path: Path) -> Iterator[Path]: ...
    def stat(self, path: Path) -> os.stat_result: ...
    def read_text(self, path: Path, *, encoding: str = "utf-8") -> str: ...
    def write_text(self, path: Path, data: str, *, encoding: str = "utf-8") -> None: ...
    def open_read(self, path: Path) -> BinaryIO: ...
    def unlink(self, path: Path) -> None: ...
    def rename(self, src: Path, dst: Path) -> None: ...
    def copy_file(self, src: Path, dst: Path) -> None: ...
